package Pojo;

public class Payload 

{
	
	public static String payload()
	{
		String str="[\r\n"
				+ "    {\r\n"
				+ "        \"id\": 1,\r\n"
				+ "        \"title\": \"Majestic Mountain Graphic T-Shirt\",\r\n"
				+ "        \"price\": 44,\r\n"
				+ "        \"description\": \"Elevate your wardrobe with this stylish black t-shirt featuring a striking monochrome mountain range graphic. Perfect for those who love the outdoors or want to add a touch of nature-inspired design to their look, this tee is crafted from soft, breathable fabric ensuring all-day comfort. Ideal for casual outings or as a unique gift, this t-shirt is a versatile addition to any collection.\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/jb5Yu0h.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/UlxxXyG.jpeg\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 2,\r\n"
				+ "        \"title\": \"Classic Red Pullover Hoodie\",\r\n"
				+ "        \"price\": 10,\r\n"
				+ "        \"description\": \"Elevate your casual wardrobe with our Classic Red Pullover Hoodie. Crafted with a soft cotton blend for ultimate comfort, this vibrant red hoodie features a kangaroo pocket, adjustable drawstring hood, and ribbed cuffs for a snug fit. The timeless design ensures easy pairing with jeans or joggers for a relaxed yet stylish look, making it a versatile addition to your everyday attire.\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"https://i.imgur.com/1twoaDy.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/FDwQgLy.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/kg1ZhhH.jpeg\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 3,\r\n"
				+ "        \"title\": \"Classic Heather Gray Hoodie\",\r\n"
				+ "        \"price\": 69,\r\n"
				+ "        \"description\": \"Stay cozy and stylish with our Classic Heather Gray Hoodie. Crafted from soft, durable fabric, it features a kangaroo pocket, adjustable drawstring hood, and ribbed cuffs. Perfect for a casual day out or a relaxing evening in, this hoodie is a versatile addition to any wardrobe.\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"https://i.imgur.com/cHddUCu.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/CFOjAgK.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/wbIMMme.jpeg\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 4,\r\n"
				+ "        \"title\": \"Classic Grey Hooded Sweatshirt\",\r\n"
				+ "        \"price\": 90,\r\n"
				+ "        \"description\": \"Elevate your casual wear with our Classic Grey Hooded Sweatshirt. Made from a soft cotton blend, this hoodie features a front kangaroo pocket, an adjustable drawstring hood, and ribbed cuffs for a snug fit. Perfect for those chilly evenings or lazy weekends, it pairs effortlessly with your favorite jeans or joggers.\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"https://i.imgur.com/R2PN9Wq.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/IvxMPFr.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/7eW9nXP.jpeg\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 5,\r\n"
				+ "        \"title\": \"Classic Black Hooded Sweatshirt\",\r\n"
				+ "        \"price\": 79,\r\n"
				+ "        \"description\": \"Elevate your casual wardrobe with our Classic Black Hooded Sweatshirt. Made from high-quality, soft fabric that ensures comfort and durability, this hoodie features a spacious kangaroo pocket and an adjustable drawstring hood. Its versatile design makes it perfect for a relaxed day at home or a casual outing.\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"https://i.imgur.com/cSytoSD.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/WwKucXb.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/cE2Dxh9.jpeg\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 6,\r\n"
				+ "        \"title\": \"Classic Comfort Fit Joggers\",\r\n"
				+ "        \"price\": 25,\r\n"
				+ "        \"description\": \"Discover the perfect blend of style and comfort with our Classic Comfort Fit Joggers. These versatile black joggers feature a soft elastic waistband with an adjustable drawstring, two side pockets, and ribbed ankle cuffs for a secure fit. Made from a lightweight and durable fabric, they are ideal for both active days and relaxed lounging.\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"https://i.imgur.com/ZKGofuB.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/GJi73H0.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/633Fqrz.jpeg\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 7,\r\n"
				+ "        \"title\": \"Classic Comfort Drawstring Joggers\",\r\n"
				+ "        \"price\": 79,\r\n"
				+ "        \"description\": \"Experience the perfect blend of comfort and style with our Classic Comfort Drawstring Joggers. Designed for a relaxed fit, these joggers feature a soft, stretchable fabric, convenient side pockets, and an adjustable drawstring waist with elegant gold-tipped detailing. Ideal for lounging or running errands, these pants will quickly become your go-to for effortless, casual wear.\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"https://i.imgur.com/mp3rUty.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/JQRGIc2.jpeg\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 8,\r\n"
				+ "        \"title\": \"Classic Red Jogger Sweatpants\",\r\n"
				+ "        \"price\": 98,\r\n"
				+ "        \"description\": \"Experience ultimate comfort with our red jogger sweatpants, perfect for both workout sessions and lounging around the house. Made with soft, durable fabric, these joggers feature a snug waistband, adjustable drawstring, and practical side pockets for functionality. Their tapered design and elastic cuffs offer a modern fit that keeps you looking stylish on the go.\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"https://i.imgur.com/9LFjwpI.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/vzrTgUR.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/p5NdI6n.jpeg\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 9,\r\n"
				+ "        \"title\": \"Classic Navy Blue Baseball Cap\",\r\n"
				+ "        \"price\": 61,\r\n"
				+ "        \"description\": \"Step out in style with this sleek navy blue baseball cap. Crafted from durable material, it features a smooth, structured design and an adjustable strap for the perfect fit. Protect your eyes from the sun and complement your casual looks with this versatile and timeless accessory.\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"https://i.imgur.com/R3iobJA.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/Wv2KTsf.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/76HAxcA.jpeg\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 10,\r\n"
				+ "        \"title\": \"Classic Blue Baseball Cap\",\r\n"
				+ "        \"price\": 86,\r\n"
				+ "        \"description\": \"Top off your casual look with our Classic Blue Baseball Cap, made from high-quality materials for lasting comfort. Featuring a timeless six-panel design with a pre-curved visor, this adjustable cap offers both style and practicality for everyday wear.\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"https://i.imgur.com/wXuQ7bm.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/BZrIEmb.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/KcT6BE0.jpeg\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    }\r\n"
				+ "]";
		return str;
	}

}
