package Pojo;

public class Payload2 

{
	
	public static String SamplePayload()
	{
		String str2="[\r\n"
				+ "    {\r\n"
				+ "        \"id\": 34,\r\n"
				+ "        \"title\": \"Modern Ergonomic Office Chair\",\r\n"
				+ "        \"price\": 71,\r\n"
				+ "        \"description\": \"Elevate your office space with this sleek and comfortable Modern Ergonomic Office Chair. Designed to provide optimal support throughout the workday, it features an adjustable height mechanism, smooth-rolling casters for easy mobility, and a cushioned seat for extended comfort. The clean lines and minimalist white design make it a versatile addition to any contemporary workspace.\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"https://i.imgur.com/3dU0m72.jpeg\",\r\n"
				+ "            \"https://i.imgur.com/zPU3EVa.jpeg\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 3,\r\n"
				+ "            \"name\": \"Furnitures\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/Qphac99.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-11T10:54:16.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 65,\r\n"
				+ "        \"title\": \"New Product\",\r\n"
				+ "        \"price\": 10,\r\n"
				+ "        \"description\": \"A description\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"[\\\"https://placeimg.com/640/480/any\\\"]\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-11T08:48:28.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-11T08:48:28.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 66,\r\n"
				+ "        \"title\": \"New Product\",\r\n"
				+ "        \"price\": 10,\r\n"
				+ "        \"description\": \"A description\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"[\\\"https://placeimg.com/640/480/any\\\"]\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-11T08:49:42.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-11T08:49:42.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 67,\r\n"
				+ "        \"title\": \"New Product\",\r\n"
				+ "        \"price\": 10,\r\n"
				+ "        \"description\": \"A description\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"[\\\"https://placeimg.com/640/480/any\\\"]\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-11T10:02:02.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-11T10:02:02.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 69,\r\n"
				+ "        \"title\": \"New Product\",\r\n"
				+ "        \"price\": 10,\r\n"
				+ "        \"description\": \"A description\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"[\\\"https://placeimg.com/640/480/any\\\"]\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-11T10:24:18.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-11T10:24:18.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 70,\r\n"
				+ "        \"title\": \"New Product\",\r\n"
				+ "        \"price\": 10,\r\n"
				+ "        \"description\": \"A description\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"[\\\"https://placeimg.com/640/480/any\\\"]\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-11T10:24:18.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-11T10:24:18.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 71,\r\n"
				+ "        \"title\": \"New Product\",\r\n"
				+ "        \"price\": 10,\r\n"
				+ "        \"description\": \"A description\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"[\\\"https://placeimg.com/640/480/any\\\"]\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-11T10:24:18.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-11T10:24:18.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 72,\r\n"
				+ "        \"title\": \"New Product\",\r\n"
				+ "        \"price\": 10,\r\n"
				+ "        \"description\": \"A description\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"[\\\"https://placeimg.com/640/480/any\\\"]\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-11T10:24:29.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-11T10:24:29.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 73,\r\n"
				+ "        \"title\": \"New Product\",\r\n"
				+ "        \"price\": 10,\r\n"
				+ "        \"description\": \"A description\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"[\\\"https://placeimg.com/640/480/any\\\"]\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-11T10:24:34.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-11T10:24:34.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 74,\r\n"
				+ "        \"title\": \"New Product\",\r\n"
				+ "        \"price\": 10,\r\n"
				+ "        \"description\": \"A description\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"[\\\"https://placeimg.com/640/480/any\\\"]\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-11T10:24:34.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-11T10:24:34.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 75,\r\n"
				+ "        \"title\": \"New Product\",\r\n"
				+ "        \"price\": 10,\r\n"
				+ "        \"description\": \"A description\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"[\\\"https://placeimg.com/640/480/any\\\"]\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-11T10:24:35.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-11T10:24:35.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 76,\r\n"
				+ "        \"title\": \"New Product\",\r\n"
				+ "        \"price\": 10,\r\n"
				+ "        \"description\": \"A description\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"[\\\"https://placeimg.com/640/480/any\\\"]\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-11T10:24:35.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-11T10:24:35.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 91,\r\n"
				+ "        \"title\": \"New Product\",\r\n"
				+ "        \"price\": 10,\r\n"
				+ "        \"description\": \"A description\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"[\\\"https://placeimg.com/640/480/any\\\"]\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-11T11:47:55.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-11T11:47:55.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 93,\r\n"
				+ "        \"title\": \"New Product\",\r\n"
				+ "        \"price\": 10,\r\n"
				+ "        \"description\": \"A description\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"[\\\"https://placeimg.com/640/480/any\\\"]\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-11T11:48:16.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-11T11:48:16.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 94,\r\n"
				+ "        \"title\": \"New Product\",\r\n"
				+ "        \"price\": 10,\r\n"
				+ "        \"description\": \"A description\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"[\\\"https://placeimg.com/640/480/any\\\"]\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-11T11:50:40.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-11T11:50:40.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"Clothes\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/QkIa5tT.jpeg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 95,\r\n"
				+ "        \"title\": \"Iphone 15\",\r\n"
				+ "        \"price\": 100000,\r\n"
				+ "        \"description\": \"Experience the iPhone 15 – your dynamic companion. Dynamic Island ensures you stay connected, bubbling up alerts seamlessly while you're busy. Its durable design features infused glass and aerospace-grade aluminum, making it dependable and resistant to water and dust. Capture life with precision using the 48 MP Main Camera, perfect for any shot. Powered by the A16 Bionic Processor, it excels in computational photography and more, all while conserving battery life. Plus, it's USB-C compatible, simplifying your charging needs. Elevate your tech game with the iPhone 15 – innovation at your fingertips. Goodbye cable clutter, hello convenience.\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"[\\\"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/h/d/9/-original-imagtc2qzgnnuhxh.jpeg?q=70&crop=false\\\"]\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-11T12:31:35.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-11T12:31:35.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 5,\r\n"
				+ "            \"name\": \"Miscellaneous\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/BG8J0Fj.jpg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 96,\r\n"
				+ "        \"title\": \"Apple iPhone 14 Pro (Deep Purple, 128 GB)\",\r\n"
				+ "        \"price\": 119000,\r\n"
				+ "        \"description\": \"Experience the iPhone 14 Pro – your dynamic companion. Dynamic Island ensures you stay connected, bubbling up alerts seamlessly while you're busy. Its durable design features infused glass and aerospace-grade aluminum, making it dependable and resistant to water and dust. Capture life with precision using the 48 MP Main Camera, perfect for any shot. Powered by the A16 Bionic Processor, it excels in computational photography and more, all while conserving battery life. Plus, it's USB-C compatible, simplifying your charging needs. Elevate your tech game with the iPhone 14 pro – innovation at your fingertips. Goodbye cable clutter, hello convenience.\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"[\\\"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/l/8/r/-original-imaghxemnnnkd8bg.jpeg?q=70&crop=false\\\"]\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-11T12:34:00.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-11T12:34:00.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 5,\r\n"
				+ "            \"name\": \"Miscellaneous\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/BG8J0Fj.jpg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 97,\r\n"
				+ "        \"title\": \"Apple iPhone 13 Pro Max (Graphite, 1 TB)\",\r\n"
				+ "        \"price\": 179900,\r\n"
				+ "        \"description\": \"iPhone 13. boasts an advanced dual-camera system that allows you to click mesmerising pictures with immaculate clarity. Furthermore, the lightning-fast A15 Bionic chip allows for seamless multitasking, elevating your performance to a new dimension. A big leap in battery life, a durable design, and a bright Super Retina XDR display facilitate boosting your user experience.\",\r\n"
				+ "        \"images\": [\r\n"
				+ "            \"[\\\"https://rukminim2.flixcart.com/image/416/416/ktketu80/mobile/j/a/x/iphone-13-pro-mlvv3hn-a-apple-original-imag6vpbngxtrvvx.jpeg?q=70&crop=false\\\"]\"\r\n"
				+ "        ],\r\n"
				+ "        \"creationAt\": \"2024-02-11T12:35:24.000Z\",\r\n"
				+ "        \"updatedAt\": \"2024-02-11T12:35:24.000Z\",\r\n"
				+ "        \"category\": {\r\n"
				+ "            \"id\": 5,\r\n"
				+ "            \"name\": \"Miscellaneous\",\r\n"
				+ "            \"image\": \"https://i.imgur.com/BG8J0Fj.jpg\",\r\n"
				+ "            \"creationAt\": \"2024-02-10T19:53:40.000Z\",\r\n"
				+ "            \"updatedAt\": \"2024-02-10T19:53:40.000Z\"\r\n"
				+ "        }\r\n"
				+ "    }\r\n"
				+ "]";
		return str2;
	}


}
